micronaut:
  application:
    name: pixKeyManagerRest

grpc:
  channels:
    pix:
      address: 'localhost:50052'
      plaintext: true
      max-retry-attempts: 10

jackson:
  serialization:
    writeDatesAsTimestamps: false